//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTrace_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iTrace_Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another service is running on port .
        /// </summary>
        public static string AnotherServiceIsRunningOnPort {
            get {
                return ResourceManager.GetString("AnotherServiceIsRunningOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate.
        /// </summary>
        public static string Calibrate {
            get {
                return ResourceManager.GetString("Calibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes require a program restart to be applied.
        /// </summary>
        public static string ChangeRequiresRestart {
            get {
                return ResourceManager.GetString("ChangeRequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse {0} as an IP Address.
        /// </summary>
        public static string CouldNotParseIPAddress {
            get {
                return ResourceManager.GetString("CouldNotParseIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Port Values.
        /// </summary>
        public static string DuplicatePortValues {
            get {
                return ResourceManager.GetString("DuplicatePortValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Screen Recording.
        /// </summary>
        public static string EnableScreenRecording {
            get {
                return ResourceManager.GetString("EnableScreenRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Reticle.
        /// </summary>
        public static string HideReticle {
            get {
                return ResourceManager.GetString("HideReticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP Address.
        /// </summary>
        public static string InvalidIPAddress {
            get {
                return ResourceManager.GetString("InvalidIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Port Value.
        /// </summary>
        public static string InvalidPortValue {
            get {
                return ResourceManager.GetString("InvalidPortValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Smarteye Port Value.
        /// </summary>
        public static string InvalidSmarteyePortValue {
            get {
                return ResourceManager.GetString("InvalidSmarteyePortValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Socket Port Value.
        /// </summary>
        public static string InvalidSocketPortValue {
            get {
                return ResourceManager.GetString("InvalidSocketPortValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Websocket Port Value&quot;.
        /// </summary>
        public static string InvalidWebSocketPortValue {
            get {
                return ResourceManager.GetString("InvalidWebSocketPortValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Monitor.
        /// </summary>
        public static string MonitorIndexIncorrectValue {
            get {
                return ResourceManager.GetString("MonitorIndexIncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected monitor must exist.
        /// </summary>
        public static string MonitorIndexOutOfRange {
            get {
                return ResourceManager.GetString("MonitorIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port values cannot be the same value!.
        /// </summary>
        public static string PortValuesCannotBeSameValue {
            get {
                return ResourceManager.GetString("PortValuesCannotBeSameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port values must be numeric!.
        /// </summary>
        public static string PortValuesMustBeNumeric {
            get {
                return ResourceManager.GetString("PortValuesMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Setup.
        /// </summary>
        public static string SessionSetup {
            get {
                return ResourceManager.GetString("SessionSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Eye Status.
        /// </summary>
        public static string ShowEyeStatus {
            get {
                return ResourceManager.GetString("ShowEyeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Reticle.
        /// </summary>
        public static string ShowReticle {
            get {
                return ResourceManager.GetString("ShowReticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smarteye port values must be in the range: .
        /// </summary>
        public static string SmarteyePortMustBeInRange {
            get {
                return ResourceManager.GetString("SmarteyePortMustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket Server Cannot Start.
        /// </summary>
        public static string SocketServerCannotStart {
            get {
                return ResourceManager.GetString("SocketServerCannotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket port values must be in the range: .
        /// </summary>
        public static string SocketValuesMustBeInRange {
            get {
                return ResourceManager.GetString("SocketValuesMustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay.
        /// </summary>
        public static string StartReplay {
            get {
                return ResourceManager.GetString("StartReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Tracking.
        /// </summary>
        public static string StartTracking {
            get {
                return ResourceManager.GetString("StartTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop that service or change the port for iTrace Core in settings and restart the Core..
        /// </summary>
        public static string StopServiceOrChangePortThenRestart {
            get {
                return ResourceManager.GetString("StopServiceOrChangePortThenRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Tracking.
        /// </summary>
        public static string StopTracking {
            get {
                return ResourceManager.GetString("StopTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record with DejaVu.
        /// </summary>
        public static string ToggleDejaVu {
            get {
                return ResourceManager.GetString("ToggleDejaVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackers:.
        /// </summary>
        public static string Trackers {
            get {
                return ResourceManager.GetString("Trackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websocket Server Cannot Start.
        /// </summary>
        public static string WebSocketServerCannotStart {
            get {
                return ResourceManager.GetString("WebSocketServerCannotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websocket port values must be in the range: .
        /// </summary>
        public static string WebSocketValuesMustBeInRange {
            get {
                return ResourceManager.GetString("WebSocketValuesMustBeInRange", resourceCulture);
            }
        }
    }
}